application:
  token_key: fg20TmaktPuWGu4C
  enable: true
  port: 8080

wechat:
  token: 40ecd7c78e67cdf292b6213ac3a3d8ac
  callback_url: https://www.youngbreezem.site

chatgtp:
  addr: chatgtp:8080
  token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik1UaEVOVUpHTkVNMVFURTRNMEZCTWpkQ05UZzVNRFUxUlRVd1FVSkRNRU13UmtGRVFrRXpSZyJ9.eyJodHRwczovL2FwaS5vcGVuYWkuY29tL3Byb2ZpbGUiOnsiZW1haWwiOiI5NDA2OTU4MzZAcXEuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWV9LCJodHRwczovL2FwaS5vcGVuYWkuY29tL2F1dGgiOnsidXNlcl9pZCI6InVzZXItU0dFQkEwT1p3QkFCM2FINUg1NWVDRWF4In0sImlzcyI6Imh0dHBzOi8vYXV0aDAub3BlbmFpLmNvbS8iLCJzdWIiOiJ3aW5kb3dzbGl2ZXwzYjgxYjRiNzYwYzExYWRmIiwiYXVkIjpbImh0dHBzOi8vYXBpLm9wZW5haS5jb20vdjEiLCJodHRwczovL29wZW5haS5vcGVuYWkuYXV0aDBhcHAuY29tL3VzZXJpbmZvIl0sImlhdCI6MTY5NDk0MzA5NSwiZXhwIjoxNjk2MTUyNjk1LCJhenAiOiJUZEpJY2JlMTZXb1RIdE45NW55eXdoNUU0eU9vNkl0RyIsInNjb3BlIjoib3BlbmlkIGVtYWlsIHByb2ZpbGUgbW9kZWwucmVhZCBtb2RlbC5yZXF1ZXN0IG9yZ2FuaXphdGlvbi5yZWFkIG9yZ2FuaXphdGlvbi53cml0ZSBvZmZsaW5lX2FjY2VzcyJ9.CgPfu7dXTh6avlR23eYca4X8whPHZW_UO_D9HVdu2pyv-MFiUhUWjGoVmVDLDCP_wUDqM7jmGbxFIz5OB6bLqK7IPm2Mb__gi8MsxbkwioqtyEGCLVLv0RQwayHecXE386EXm-0zYafjEAyT8V3TMRpg2ZXEv_CMyZ3naN4at5KQK2StWu1bt9NjbvT6AqQDW2YysLKq429R-yDe4l8ODEIBk10j71h5bH5ikNhnqP0Y-Rg6iklmXUuBJzgfJjOzVxJVILayJP6ejgdcSJ5YzFTWzgZpeIdHh6tPhpFnbuyWV0vLkRPeF5QHAdN9XffS7eQQLkG_C5ZsCIcyoCpk7A

mysql:
  dst: root:root4me2@/ai_box?charset=utf8&parseTime=True&loc=Local

redis:
  host: localhost
  port: 6379
  password: root
  db: 0

mongo:
  addr: mongodb://localhost:27017
